services:
  - type: web
    name: grok-playground
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 180 --workers 1 --bind 0.0.0.0:$PORT web_app:app
    envVars:
      - key: REQUEST_TIMEOUT
        value: 180
      - key: WORKER_TIMEOUT
        value: 1800
    plan: starter  # or higher tier
